version: "3.8"
services:
  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fripa
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/data.sql:/docker-entrypoint-initdb.d/2.sql"